### ISSUE TITLE
Is there a way to focus a window by name?

### ISSUE THREAD

**Issue by violinner** [electron/spectron#108]
If an application starts and opens a number of windows, 
is there a way to find one by its window title and focus that widow?

**Comment by kevinsawicki** [comment]
Have you tried `app.client.window('my title')`?

http://webdriver.io/api/protocol/window.html

**Comment by violinner** [comment]
I have tried app.client.window('my title').

The documentation says this form of the command works with tabs.

My application has separate windows, and while
 app.client.windowByIndex( int ) works,
 app.client.window( 'string' ) does not.
