### ISSUE TITLE
Unable to Load Electron API

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/spectron#111]
I am trying to use Spectron to test an Electron app, but I am having issues getting started. The app in question has nodeIntegration disabled, so I am using a preload script as suggested in the documentation:

```javascript
const nodeReq = require
process.once('loaded', () => {
  if (process.env.NODE_ENV === 'test') {
    window.electronRequire = nodeReq
  }
})
```
Through debugging, I can confirm that this is running and having the intended result. My issue occurs when Spectron attempts to retrieve the [Electron api](https://github.com/electron/spectron/blob/master/lib/api.js#L68). As far as I can tell, it is failing on ``require('electron')``/``window['electronRequire']('electron')``. I am not sure why this is happening. When I use the Chromium debugger tools to see what ``window['electronRequire]`` is being set to, I get:
```javascript
function require(path) {
    return self.require(path);
  }
```
And as far as I can tell, this is the node require. Some other details about my env:
- Node version: 4.1.1
- Electron version: 0.34.1
- Spectron version: 3.3.0
- Testing against an executable

Finally, if I add Electron to my dependencies, ``window['electronRequire]('electron')`` does end up working, except it finds ``electron.exe``, which Spectron doesn't seem to know what to do with.

**Comment by kevinsawicki** [comment]
Are you specifying the `requireName: 'electronRequire'` option to the `Application` constructor?

**Comment by MRayermannMSFT** [comment]
It definitely turned out to be an Electron version issue. Once we updated to 1.3.x the API was able to load.
