### ISSUE TITLE
command to run the test

### ISSUE THREAD

**Issue by patricia5859** [electron/spectron#115]
Hello,

I did go through the documentation for Spectron but did not find a command to run the tests. 
Could someone post it here.
Thanks!

**Comment by MarshallOfSound** [comment]
Spectron isn't a test runner.  You have to use a runner like `mocha` and use Spectron in your tests.

See the examples for [Ava](https://github.com/electron/spectron#with-ava) and [mocha](https://github.com/electron/spectron#with-chai-as-promised)
