### ISSUE TITLE
Mocha requires Electron to be installed globally

### ISSUE THREAD

**Issue by patricia5859** [electron/spectron#116]
Hello,

I used mocha to test my Electron app and got an error: "Can not find 'electron' in the $PATH and $ELECTRON_PATH is not set. Please either set $ELECTRON_PATH or 'npm install electron'". My workspace contains electron and not the machine itself. Is there a way I could circumvent the installation of Electron on my build machine? As, Electron will in turn require Node and NPM on the build machine. I am not sure if Spectron can help achieve the goal.
Thanks!

**Comment by MarshallOfSound** [comment]
> As, Electron will in turn require Node and NPM on the build machine

How do you imagine you would run `mocha` tests with node and NPM?

Also when you say mocha I think you mean `electron-mocha`.  To use that tool you need to either `npm install electron` or just `npm install` with Electron in your package.json.

Regardless however, if you have issues with `electron-mocha` please raise them on the [correct repository](https://github.com/jprichardson/electron-mocha).

> I am not sure if Spectron can help achieve the goal.

Spectron runs in whatever test runner you want, it is test runner agnostic as it were 👍
