### ISSUE TITLE
Default example doesn't work on windows machine. 

### ISSUE THREAD

**Issue by etiennejcharles** [electron/spectron#127]
Thanks for the great tool there !

When I install mocha, and run the default example, it doesn't work on my windows machine, 
In order for it to work I had to do the 2 things.

1) Get the Electron Path
2) Also add the default path to my Electron App as a First Argument. 

Shouldn't  the default example include that ? 
i.e

```
var Application = require('spectron').Application;
var assert      = require('assert');
var path        = require('path');


describe('application launch', ()=> {
    this.timeout(10000)

    beforeEach(()=> {
        this.app = new Application({
            path: getElectronPath(),
            args: [path.join(__dirname, '..')]
        })
        return this.app.start();
    });

    afterEach(()=> {
        if (this.app && this.app.isRunning()) {
            return this.app.stop()
        }
    })


    it('shows an initial window', ()=> {
        return this.app.client.getWindowCount().then(function (count) {
            assert.equal(count, 1)
        });
    })

    function getElectronPath() {
        let electronPath = path.join(__dirname, '..', 'node_modules', '.bin', 'electron');
        if (process.platform === 'win32')  electronPath += '.cmd';
        return electronPath;
    }
});
```

I would gladly do a PR if  you agree necessary

**Comment by sktzofrenic** [comment]
I agree that it's necessary. This post ended about 3-4 hours of head scratching.

**Comment by hovancik** [comment]
There is a better way: https://github.com/electron/spectron/issues/86

```

let electronPath = require('electron')
....

    this.app = new Application({
      path: electronPath,
      args: [
        path.join(__dirname, '..', 'app')
      ]
    })

```

**Comment by sktzofrenic** [comment]
That is indeed a better way. Either way, something should be added to the docs.

**Comment by zeke** [comment]
@etiennejcharles please do submit a PR!

**Comment by JohnBerlin** [comment]
OH god, thanks for this... I was about to throw my debugger in the trash.

**Comment by JohnBerlin** [comment]
@etiennejcharles by the way, your sample code has a bug: using an arrow function makes you lose the mocha context `this.timeout`
`describe('application launch', function () {
    this.timeout(10000)
...`

**Comment by Sigiller** [comment]
Hi! When I try to run this example, test failing with error:
> Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

Application was started, but test hasn't been executed. How fix it?

My code:
`const Application = require('spectron').Application;
const assert = require('assert');
const electronPath = require('electron-prebuilt');
const path = require('path');

describe('application launch', function () {
    this.timeout(10000);

    beforeEach(function () {
        this.app = new Application({
            path: electronPath,
            args: [
                path.join(__dirname, '..', 'app')
            ]
        });
        return this.app.start();
    });

    afterEach(function () {
        if (this.app && this.app.isRunning()) {
            return this.app.stop()
        }
    });

    it('shows an initial window', function () {
        console.log(this.app.client.getWindowCount());
        return this.app.client.getWindowCount().then(function (count) {
            assert.equal(count, 1)
        })
    })
});
`

**Comment by etiennejcharles** [comment]
Thanks for the comment @JohnBerlin  Il do a pull ASAP!

**Comment by etiennejcharles** [comment]
Pull request created ;) https://github.com/electron/spectron/pull/141
