### ISSUE TITLE
client.click is not implemented?

### ISSUE THREAD

**Issue by PolarisMiura** [electron/spectron#128]
I want to click an element which exists certainly by checking with client.element(selector).
But click event is not triggered by client.click(selector).

I implemented this like following code based on the document,
http://webdriver.io/api.html
http://webdriver.io/api/action/click.html

Code:
`....

app.client.element('#MyElementId').then( (e)=> {
      // O.K. reached
      console.log('#MyElementId exists')
      app.client.click('#MyElementId').then(()=> {
           // not reach
      })
      // OR
      app.client.click('#MyElementId');
      setTimeout(()=>{
            // not reach
      },3000);
});

// OR using elements()
app.client.elements('.MyElementClassname').then( (elements)=> {
      // not reach, timeout occured
      // elements() also is not implemented?
})
`

Is client.click not implemented yet?...

**Comment by PolarisMiura** [comment]
More additional info,

The click target is a radio button, and click for the label element of that radio is fired by app.client.click.
I don't know why client.click(radio) is not tirggered...

**Comment by zeke** [comment]
This might do the trick: http://webdriver.io/api/state/isSelected.html

**Comment by PolarisMiura** [comment]
Thank you so much!!
I solved it!
