### ISSUE TITLE
Possible to run packaged Windows app?

### ISSUE THREAD

**Issue by achrist** [electron/spectron#134]
I was playing around with spectron and I noticed you can specify a path directly to the Mac app. Seen in the example code from the README:

```
beforeEach(function () {
    this.app = new Application({
      path: '/Applications/MyApp.app/Contents/MacOS/MyApp'
    })
    return this.app.start()
  })
```

Can the same thing be done for a packaged Windows app as well? I have tried pointing spectron to the app's .exe file but it doesn't seem to work. It doesn't seem to be able to open the app and the tests just timeout. All the examples I've seen for Windows point spectron to electron itself and then specify the app path via the args param. Like here for example: https://github.com/electron/spectron/issues/127. Is this the only way it can be ran for Windows?

**Comment by pri2si17-1997** [comment]
@achrist Have you solved this issue?

**Comment by achrist** [comment]
@pri2si17-1997 I never did. I just ended up running it via pointing to the electron itself and then specified the app path.

**Comment by pri2si17-1997** [comment]
Ohh.. ok. That works. @achrist
