### ISSUE TITLE
Error: ChromeDriver did not start within 5000ms

### ISSUE THREAD

**Issue by devwithin** [electron/spectron#144]
I'm trying to run the getting started script from [here](https://github.com/electron/spectron/blob/master/README.md#using) (slightly modified).
```javascript
const Application = require("spectron").Application;
const path = require("path");
const assert = require("assert");

const electronPath = require("electron");
const appPath = path.join(__dirname, "..");

const app = new Application({
  path: electronPath,
  args: [appPath]
});

describe("application launch", function () {
  this.timeout(15000);

  beforeEach(function () {
    return app.start();
  });

  afterEach(function () {
    if (app && app.isRunning()) {
      return app.stop();
    }
  });

  it("shows an initial window", function () {
    return app.client.getWindowCount().then(function (count) {
      assert.equal(count, 1);
    });
  });
});
```

I've tried to run this script but I'm getting following error

```
bash-3.2$ ./node_modules/.bin/mocha ./test/main.js 


  application launch
    1) "before each" hook for "shows an initial window"


  0 passing (6s)
  1 failing

  1) application launch "before each" hook for "shows an initial window":
     Error: ChromeDriver did not start within 5000ms
      at Error (native)
      at node_modules/spectron/lib/chrome-driver.js:63:25
      at Request._callback (node_modules/spectron/lib/chrome-driver.js:121:45)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

I'm on osx 10.11 with
* Electron 1.4.8
* Spectron 3.4.0
* Mocha 3.1.2
* node 6.5 and npm 3.10

**Comment by Siilwyn** [comment]
I'm having the same issue but on a Docker container running [node:6](https://github.com/nodejs/docker-node/blob/d20d305f0bf5935385a32558501f3a5c65e34878/6.9/Dockerfile). I have installed `xvfb`.
Simplified commands I run before testing are:
```
 - "apt install -y xvfb"
 - "export DISPLAY=:99.0"
 - "Xvfb &"
 - "sleep 3"
```

- Electron 1.3.3
- Spectron 3.4.0
- Ava 0.17.0

**Comment by armoucar** [comment]
Same issue... 'ChromeDriver did not start within 5000ms'

**Comment by armoucar** [comment]
I could get ChromeDriver working by adding a proxy exception in my terminal.

    export {no_proxy,NO_PROXY}="127.0.0.1"

**Comment by Siilwyn** [comment]
Sadly that did not solve the issue for me. @armoucar how is that related? Maybe I can try out some other things related to it.

**Comment by armoucar** [comment]
At work I have to have proxies configuration on my terminal and I think ChromeDriver is a server running locally... When at home, with all proxies deactivated, I tested the same project I was trying to run the tests and it worked normally. I could then assume it was a proxy problem, in my case.

**Comment by jwood803** [comment]
@devwithin @armoucar Is the application not starting at all when running the tests?

**Comment by armoucar** [comment]
In my environment you demo works fine, as long as I set my `locahost,127.0.0.1` proxy exceptions.

**Comment by Siilwyn** [comment]
@jwood803 your demo doesn't work for me but it seems to be an issue in the test file:
https://gitlab.com/Siilwyn/spectron-test-gh-project/builds/7790833

**Comment by devwithin** [comment]
@armoucar Thanks a lot. Your solution worked for me.
``` 
export {no_proxy,NO_PROXY}="127.0.0.1,localhost"
```

Turns out this was a problem with proxy setting.

**Comment by jwood803** [comment]
@Siilwyn Interesting! I haven't seen that error locally. Simple fix, though :)

**Comment by Siilwyn** [comment]
Can this be re-opened please? I'm still struggling with the same problem.
The logs: https://gitlab.com/Siilwyn/try-building-electri/builds/8062089

Or should I open a new issue?

**Comment by devwithin** [comment]
@Siilwyn I'll reopen this issue as your problem looks very similar to mine.

I suspect that this might be because of some network or proxy config problem.

**Comment by Siilwyn** [comment]
@devwithin thank you!
Would you know any way to get more debugging info out of it so I can check if it's a network problem? It's weird that `export {no_proxy,NO_PROXY}="127.0.0.1,localhost"` works for you but not for me.

**Comment by jwood803** [comment]
That is weird, indeed. I've never even needed to use that in any of my tests.

**Comment by akashnimare** [comment]
@Siilwyn could you please tell me why it's failing - logs - https://travis-ci.org/zulip/zulip-electron/jobs/189773598

**Comment by Siilwyn** [comment]
@akashnimare your error is not related to the issue described above. And sorry I don't know why it's failing.

**Comment by BenBergman** [comment]
I'm experiencing the same error as Siilwyn, but when I try to install the packages he mentions I get errors that such packages do not exist. I am using the `node:9` docker container instead of 6. The proxy solution is also not working for me.

**Comment by BenBergman** [comment]
I ended up using a different docker image which was already setup for doing headless electron testing: `aheuermann/electron`

**Comment by gireeshcse** [comment]
Same Issue Error: ChromeDriver did not start within 5000ms

In Windows set the environmental variable 
**NO_PROXY** to **127.0.0.1,localhost**

This is a proxy problem as said by @armoucar 
thanks  a lot @armoucar

**Comment by HaNdTriX** [comment]
I had a similar problem, after switching from mocha to ava. Reinstalling all `node_modules` solved the issue for me.

```bash
yarn install --force
```

**Comment by artemv** [comment]
In my case (spectron 5.0.0) solution was to run `yarn upgrade spectron` which upgraded webdriverio and some other spectron' deps (but not spectron itself)

**Comment by daisyjanepueblos** [comment]
> I had a similar problem, after switching from mocha to ava. Reinstalling all `node_modules` solved the issue for me.
> 
> ```shell
> yarn install --force
> ```

this helped me! thanks!

**Comment by majedur-rahaman** [comment]
I just removed that runner and started fresh one. New Runner downloaded Spectron and ChromeDriver on start and Chrome worked.
