### ISSUE TITLE
app.client.getWindowCount() includes an extra window for electron-react-devtools

### ISSUE THREAD

**Issue by scottrippey** [electron/spectron#147]
I'm using [electron-react-devtools](https://github.com/firejune/electron-react-devtools) for my react app.
When I call `app.client.getWindowCount()`, it returns 2 windows; the 2nd window has the url `chrome-extension://react-developer-tools/_generated_background_page.html`

This is causing some issues for my tests, since I don't want to count that page as an actual window.
Is there any way to ignore this window for all Window commands (eg. `windowByIndex`)?

**Comment by MarshallOfSound** [comment]
@scottrippey This has been discussed before and TLDR: no.  The API currently acts as expected (the background page is technically it's own window).  If you don't want your tests to include this window, don't install the devtools in your tests.

Or you yourself can apply a filter to the returned windows and exclude the ones you want.

**Comment by scottrippey** [comment]
Ok, thank you for the fast response.  I was considering the filter approach.  Do you have any recommendation on what criteria to filter by?  Is there any easy way to identify non-app windows like this?
I'm considering using `getUrl()`, and filtering by the `chrome-extension://` protocol.

**Comment by scottrippey** [comment]
@MarshallOfSound Do you have any suggestions for the above?  I'm still not sure if there's a better way to handle number 1 above?  (number 2 is looking to be viable)

Also, is there any alternative to `switchTabs` that lets me specify which window I want to switch to?  Seems like maybe `switchTabs` is occasionally switching to the dev-tools.
