### ISSUE TITLE
Is there a way to wait until new window fully loaded?

### ISSUE THREAD

**Issue by bittergeek** [electron/spectron#152]
I'm testing the scenario where a new window is created upon button click.
```
app.client.waitUntilWindowLoaded()
                .click('#sginin-button')
...
...
                // to get the new window?
                .windowByIndex(1)
               .getTitle().should.eventually.equal('SignIn Window');
```
How do I make the test wait until the new window is fully loaded then check the title among other things in the new window?

Many thanks

**Comment by tiemevanveen** [comment]
I think you could use webdriver's [`waitUntil`](http://webdriver.io/api/utility/waitUntil.html), and check how it's used to implement [`waitUntilWindowLoaded`](https://github.com/electron/spectron/blob/fdbde39b4808896bb7bf2c8ab760eb60e84b1fcf/lib/application.js#L214-L223
).

I haven't tested this, but maybe something like this might work or gives you some inspiration :) 


    app.client
      .waitUntilWindowLoaded()
      .click('#sginin-button')
      .waitUntil(function () {
        return app.client.windowByIndex(1).isLoading().then(function (loading) {
          return !loading
        })
      })
      .getTitle().should.eventually.equal('SignIn Window');

**Comment by bittergeek** [comment]
Thanks for the suggestion.

The following seems to work in the end:

```
.waitUntil(function () {
        return this.windowHandles().then(getResponseValue).then(function (handles) {
            return handles.length === 2;
        })
    }, 10000).then(function () { }, function (error) {
        error.message = 'waitUntilTwoWindows ' + error.message
        throw error
})
```

**Comment by tiemevanveen** [comment]
Nice, glad I could help!

**Comment by MarshallOfSound** [comment]
Appears to be resolved 👍
