### ISSUE TITLE
`webContents` not set in Application.

### ISSUE THREAD

**Issue by evertonfraga** [electron/spectron#157]
When running an App test suite *– using spectron 3.4.0, electron 1.3.13* – I get:

`waitUntilWindowLoaded: Cannot read property 'isLoading' of undefined`
https://github.com/electron/spectron/blob/v3.4.0/lib/application.js#L214-L223

That happens both running my built version of my app and the `node_modules/.bin/electron`. I saw that spectron recently had issues with `webContents.isLoading()`, but that seemed to be fixed.

Any ideas? Thanks.

**Comment by MarshallOfSound** [comment]
Might not be the issue but in the README

> This minor version of this library tracks the minor version of the Electron versions released. So if you are using Electron 1.0.x you would want to use a spectron dependency of ~3.0.0 in your package.json file.

If you are using `1.3.13` you probably want `3.3.x` 👍

**Comment by evertonfraga** [comment]
Yep, that worked! yarn was resolving a newer version of Spectron.

Thanks a bunch.

**Comment by evertonfraga** [comment]
@MarshallOfSound it seems i'm having this issue again. But the version matching seems to be fine.

Any ideas here? Thanks

```
$ yarn list | grep "ectron"
├─ asar-electron-builder@0.13.5
├─ electron-builder-core@11.2.1
├─ electron-builder-http@12.1.0
├─ electron-builder-util@12.1.0
│  ├─ electron-builder-http@~12.1.0
├─ electron-builder@12.2.2
│  ├─ asar-electron-builder@^0.13.5
│  ├─ electron-builder-core@11.2.1
│  ├─ electron-builder-http@12.1.0
│  ├─ electron-builder-util@12.1.0
│  ├─ electron-download-tf@3.1.0
│  ├─ electron-macos-sign@~1.5.0
├─ electron-chromedriver@1.6.0
│  ├─ electron-download@^3.1.0
│  ├─ electron-download@3.3.0
├─ electron-download-tf@3.1.0
├─ electron-download@3.0.1
├─ electron-macos-sign@1.5.0
├─ electron-version@1.1.0
├─ electron-window-state@4.0.1
├─ electron@1.6.2
│  ├─ electron-download@^3.0.1
├─ spectron@3.6.1
│  ├─ electron-chromedriver@~1.6.0
│  ├─ electron-version@^1.1.0
```

**Comment by evertonfraga** [comment]
Fixed. It seems that a regression made the wrong window be focused at the time.

**Comment by nj-neer** [comment]
Encountering a similar issue when **nodeIntegration** is set to **false**

Not sure if this is an expected behaviour 

```
this.browserWindow = new BrowserWindow({
      webPreferences: {
        nodeIntegration: false,
      }
    });
```

Failing test :
```
1) Opening editor
       opens a window:
     TypeError: waitUntilWindowLoaded Cannot read property 'isLoading' of undefined
      at waitUntil(<Function>, ) - C:\Users\cdelaunay\Desktop\Carnelian\node_modules\spectron\lib\application.js:229:17

  2) Opening editor
       "after each" hook for "opens a window":
     TypeError: Cannot read property 'exit' of undefined
      at Object.stopApp (test\hooks.js:26:29)
      at Context.afterEach (test\open_editor.js:11:17)
```
