### ISSUE TITLE
Failing tests on travis(linux)

### ISSUE THREAD

**Issue by akashnimare** [electron/spectron#158]
It works perfectly on macOs. Here is the log-
https://travis-ci.org/zulip/zulip-electron/jobs/189770648

But for some reason it fails on linux. 
Logs - https://travis-ci.org/zulip/zulip-electron/jobs/189770553 

test.js
```js
const assert = require('assert')
const Application = require('spectron').Application

describe('application launch', function () {
  this.timeout(15000)

  beforeEach(function () {
    this.app = new Application({
      path: require('electron'),
      args: [__dirname + '/../app/main/index.js']
    })
    return this.app.start()
  })

  afterEach(function () {
    if (this.app && this.app.isRunning()) {
      return this.app.stop()
    }
  })

  it('shows an initial window', function () {
    return this.app.client.getWindowCount().then(function (count) {
      assert.equal(count, 1)
    })
  })
})
```
Here is app I'm working on - [zulip-electron](https://github.com/zulip/zulip-electron)

@kevinsawicki could you please tell me what I'm doing wrong?

**Comment by MarshallOfSound** [comment]
@akashnimare You should log out the URL's of the windows that the webdriver is identifying.  You are probably launching either a `webview` or a dev tools extension background page.

**Comment by akashnimare** [comment]
> You should log out the URL's of the windows that the webdriver is identifying.

@MarshallOfSound I'm not sure if this is the problem. Btw everything works perfectly if I test it locally on Ubuntu 14.04 but on travis it keeps failing :(

**Comment by akashnimare** [comment]
@MarshallOfSound I just tested it against a static file (index.html) and it's not failing. I think you're right. The actual cause of this problem is the webview.

**Comment by akashnimare** [comment]
I still don't know why loading a webview works perfectly in OSX both locally and on travis.
