### ISSUE TITLE
Spectron Broken by Electron v1.5.0

### ISSUE THREAD

**Issue by colinskow** [electron/spectron#160]
After upgrading to Electron v1.5.0 Spectron tests are broken. The selenium driver fails to connect and Spectron launches 10 Electron windows.

Using: MacOS, Node 6.9.4, Spectron 3.4.1

It works as expected again after downgrading to Electron v1.4.15.

https://github.com/electron/electron/issues/8516

```
(node:2490) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 1): 
Error: Client initialization failed after 10 attempts: 
RuntimeError Client initialization failed after 10 attempts:
```

**Comment by MarshallOfSound** [comment]
From the README

> This minor version of this library tracks the minor version of the Electron versions released. So if you are using Electron 1.0.x you would want to use a spectron dependency of ~3.0.0 in your package.json file.

I.e. In order for Spectron to use the correct chromedriver for Electron `1.5.x` we need a `3.5.x` series of Spectron

/cc @kevinsawicki Can we publish the required minor bump here even through `1.5` is still in beta?

**Comment by kevinsawicki** [comment]
> Can we publish the required minor bump here even through 1.5 is still in beta?

Sure can, will open a pull request now and see if it builds.

**Comment by kevinsawicki** [comment]
Spectron 3.5.0 has been published, can you give it a try?

**Comment by colinskow** [comment]
Different error this time... At least it doesn't open 10 electron instances.

```
(node:10362) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
Error: ChromeDriver did not start within 5000ms
```

**Comment by colinskow** [comment]
Never mind, it works now. I had to `rm -rf` node_modules and reinstall to get Electron to get them to upgrade correctly.

**Comment by zeke** [comment]
I also just ran into `ChromeDriver did not start within 5000ms` error.

Like @colinskow said `rm -rf node_modules && npm i` fixed it.

**Comment by cganpule** [comment]
Still getting same error 
"Unhandled promise rejection (rejection id: 1): Error: ChromeDriver did not start within 5000ms"

electron: 1.6.2
spectron: 3.6.0
