### ISSUE TITLE
Test module that needs dom

### ISSUE THREAD

**Issue by zolem** [electron/spectron#167]
Maybe I'm missing something but I need to test a module that uses jquery. How do I make the module actually use the DOM and still keep it isolated?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

This is more of a general "how do I test DOM modules" kind of question.  Personally, I would point you towards something like `electron-mocha` which runs your tests inside Electron.  Then you can run your mocha tests inside an actual Electron renderer process 👍
