### ISSUE TITLE
what it's the better way to test an app using travis

### ISSUE THREAD

**Issue by rafaelleru** [electron/spectron#168]
I wrote a simple test from the example in README.md and pass in my computer but travis doesn't pass it beacuse the bin files doesn't exist on the github repo. I think the fast solution it's upload the binaries but there are so big files and doesn't look very elegant. Any oher idea about how to do this correctly?

**Comment by petrvecera** [comment]
I don't understand what you mean by bin files ? Like your application ?  Like what this has to do with Spectron...

And the test requires should be in the app.json and you should run `npm install` before running your tests.

**Comment by hanneskaeufler** [comment]
I think you can do something like:

```javascript
var electronPath = "./node_modules/.bin/electron";
var appPath = __dirname + "/main.js";
var app = new Application({
            path: electronPath,
            args: [appPath]
});
```
with the proper paths to you entry script and the electron binary.
