### ISSUE TITLE
Testing multiple electron instances with Spectron

### ISSUE THREAD

**Issue by rochadt** [electron/spectron#171]
Is this possible? I would basically like to have two instances of Spectron running the same electron application. I realize that I need to set separate user-data locations for each of the electron applications. The issue that I'm running into is that both the Spectron applications start, but functions like .click() do not work on the second application instance. Any guidance here?

**Comment by rochadt** [comment]
This seems to have been an issue with the logic I was executing, and appears to work correctly.

**Comment by abaltzois** [comment]
Can you please describe the way you did it? Because I am trying to use multiremote of webdriver.io but I cannot make it work.
