### ISSUE TITLE
Electron app starting twice after upgrade to 3.6.1

### ISSUE THREAD

**Issue by furmk** [electron/spectron#182]
In my test file my beforeEach() method looks as follows:
` beforeEach(() => {
        app = new Application({
            path: config['electron-path']
        }); 
        return app.start();
    });` 

 and it was working fine before updating to 3.6.1. After update my electron application is starting twice. I though that maybe test is run twice, but after console.log() debbuging, I see that all methods are called only once. 

Downgrading to 3.6.0 fixed the problem.

**Comment by kevinsawicki** [comment]
Thanks for reporting this, this should be fixed in 3.6.2
