### ISSUE TITLE
Starting application with "electron ." instead of "npm start"

### ISSUE THREAD

**Issue by lormitto** [electron/spectron#196]
Hi,

Is there any way to force starting electron for testing with "electron ."? Should there be a choice how app is started?
The problem I face under Windows OS is related to recompiled SQLite. I cannot start my electron app with npm start but fortunately i can with "electron .". It generates another issue related to testing which I wanted to add using Spectron.

Thank you for help in advance.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW typically `npm start` maps to `electron .` in your package.json.
