### ISSUE TITLE
Basic Test doesn't work

### ISSUE THREAD

**Issue by cliff76** [electron/spectron#20]
Hi,

I am trying to get a basic test working as per the documentation. I've copied/pasted from the README and adjusted my path to point to the Electron executable but I get a test failure. Here's my test code:

```
/**
 * Created by Clifton Craig on 4/30/16.
 */
describe('Initial spec', function () {
    it('Should be easy to test.');
});

var Application = require('spectron').Application;
var assert = require('assert');

describe('application launch', function () {
    this.timeout(10000);

    beforeEach(function () {
        this.app = new Application({
            path: '/Applications/Electron.app/Contents/MacOS/Electron'
        });
        return this.app.start()
    });

    afterEach(function () {
        if (this.app && this.app.isRunning()) {
            return this.app.stop()
        }
    });

    it('shows an initial window', function () {
        return this.app.client.getWindowCount().then(function (count) {
            assert.equal(count, 1)
        })
    })
});
```

And here's the output:
```
SFO1212474815A:nightmare 212474815$ npm test

> nightmare@1.0.0 test /Users/212474815/dev/nightmare
> mocha



  Initial spec
    - Should be easy to test.

  application launch
    1) "before each" hook for "shows an initial window"


  0 passing (5s)
  1 pending
  1 failing

  1) application launch "before each" hook for "shows an initial window":
     Error: ChromeDriver did not start within 5000ms
      at Error (native)
      at node_modules/spectron/lib/chrome-driver.js:58:25
      at Request._callback (node_modules/spectron/lib/chrome-driver.js:116:45)
      at Request.self.callback (node_modules/request/request.js:200:22)
      at Request.<anonymous> (node_modules/request/request.js:1067:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:988:12)
      at endReadableNT (_stream_readable.js:905:12)



npm ERR! Test failed.  See above for more details.

```
Is there something I've missed from the documentation? Do I need to start ChromeDriver separately? I've never used ChromeDrive or WebDriver before. This is my 1st take at automated Electron testing. Thanks for any/all clarification!

**Comment by cliff76** [comment]
For some reason it started working when I opened a new terminal window. There must have been a foul env var at play. I'm closing this issue. My apologies!

**Comment by Bharadwaj108** [comment]
Hello,I exactly have the similar issue and my test case output is like this
`Test Name:	Test Suite 1 Test 1
Test Outcome:	Passed
Result StandardOutput:	
mocha.json options file not found. Using default values: { ui: 'tdd', reporter: 'tap', timeout: 2000 }
1..1
ok 1 Test Suite 1 Test 1
# tests 1
# pass 1
# fail 0
`
I have created a mocha.opts file in my test directory and set a default time out to 10000 ms also I have modified my package.json script section and have inserted these statements 
`"test": "mocha 'test/**/*.js' --timeout 10000",
    "test-debug": "mocha --debug 'test/**/*.js' --timeout 10000"`
Also I have modified the mocha.js file and changed the default time out from 2000 to 20000 ms but still nothing happens and still get the same issue. Am I missing anything here.
