### ISSUE TITLE
Failed to run on W10 64bits

### ISSUE THREAD

**Issue by adelitofarias** [electron/spectron#200]
![captura de tela de 2017-05-26 12-45-48](https://cloud.githubusercontent.com/assets/19351435/26501925/5291f1ca-4211-11e7-8e1b-ee0b4c76fcfd.png)

Hello people !!!
Well, we're having trouble running the spectrum on Windowns 10 64bit.
No ubuntu works quietly.
Has anyone noticed this error?

**Comment by brunonf15** [comment]
Hello, I also had this problem.

I solved this problem by changing the electron path
Please, try something like this ...

```
// Windows path
Const electronPath = path.join (__ dirname, '..', 'node_modules', 'electron', 'dist', 'electron.exe');
```

**Comment by adelitofarias** [comment]
Excellent !!!
Congratulations to those involved!
Topper solution !!!
