### ISSUE TITLE
spectron.d.ts needs to be updated

### ISSUE THREAD

**Issue by dschaefer** [electron/spectron#201]
Electron now ships with it's own electron.d.ts. spectron.d.ts seems to refer to types/electron which is not the same (and itself conflicts with the new one in electron). In particular, I get:

node_modules/spectron/lib/spectron.d.ts(165,27): error TS2694: Namespace 'Electron' has no exported member 'ElectronMainAndRenderer'.

And indeed Electron does not have such a member. I guess the closest thing would be AllElectron.

**Comment by zeke** [comment]
@dschaefer can you share the application code you're using that generates this error?

**Comment by dschaefer** [comment]
I have worked around it in my repos on github. I'll hack at one of them and get it into a reproduceable state.

**Comment by abhinav2004** [comment]
@zeke It is reproducible if we use the newer d.ts provided by electron itself. I am using electron v1.6.11. You can refer to this repo: https://github.com/abhinav2004/spectron-dt-1.6.11

As @dschaefer said the closest thing to ElectronMainAndRenderer is AllElectron

**Comment by kevinsawicki** [comment]
Fixed by #209 and #211 and released in 3.7.2
