### ISSUE TITLE
Allow calling setPath('userData', path) before app.start()

### ISSUE THREAD

**Issue by DutchKevv** [electron/spectron#202]
Maybe its impossible cause of the structure off Electron,

But when I run tests, I want to use a 'temp' userData folder, instead of the 'official' one, so that data from tests does not mix with installed application data.

Is this possible?

Right now its only possible to call `app.electron.remote.app.setPath('userData', path);` after app.start, cause otherwise app.electron is not defined, and thus to late.

Thanks!

**Comment by vanessayuenn** [comment]
Hi @DutchKevv, you're correct that `app.electron` isn't available until after `app.start` is called. However, you can pass in environment variables as you bootstrap the app with Spectron, e.g.:
```
const app = new Application({
  path: '<electron app path here>',
  env: {
    SPECTRON_TEMP_DIR: tempPath
  }
})
```
You can then modify your electron app code to override the `userData` path based on the environment variable being passed in.

**Comment by lukehaas** [comment]
If anyone else has this same issue, it can actually be solved by using `chromeDriverArgs` like this:
```
const app = new Application({
  path: '<electron app path here>',
  chromeDriverArgs: ['user-data-dir=/your path']
})
```
