### ISSUE TITLE
How do you debug your tests?

### ISSUE THREAD

**Issue by davidlivingrooms** [electron/spectron#207]
I'm trying to debug the following simple test. My tests run just fine and pass but I never get an opportunity to debug anything. What exactly is app.client.debug() supposed to do? It doesn't seem to do anything for me. Am I supposed to connect a debugger externally somehow instead? Here is my test file:

```javascript
const Application = require('spectron').Application
const path = require('path')
const chai = require('chai')
const chaiAsPromised = require('chai-as-promised')

let appPath = path.join(__dirname, '..', 'Gistbar-darwin-x64', 'Gistbar.app', 'Contents', 'MacOS', 'Gistbar')

if (process.platform === 'win32') {
  appPath += '.cmd'
}

const app = new Application({
  path: appPath,
})

global.before(function () {
  chai.should()
  chai.use(chaiAsPromised)
})

describe('Base Tests', function () {
  beforeEach(function () {
    return app.start()
  })

  afterEach(function () {
    return app.stop()
  })

  it('opens a window', function () {
    app.client.debug()
    return app.client.waitUntilWindowLoaded()
      .getWindowCount().should.eventually.equal(1)
  })
})
```

Can anybody shed some light on how to properly debug spectron tests? I think that the documentation around "How to debug tests" could be improved a bit. I wouldn't mind submitting a PR for "How to debug tests" to the main readme if someone teaches me how first 😃

**Comment by stepbeta** [comment]
Using VSCode this is my launch.json entry for testing spectron tests:
```javascript
{
    "name": "debug E2E Tests",
    "type": "node",
    "request": "launch",
    "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
    "stopOnEntry": false,
    "args": ["test/**/*.e2e.js", "--no-timeouts", "--require", "babel-polyfill", "--compilers", "js:babel-register"],
    "cwd": "${workspaceRoot}",
    "runtimeExecutable": null,
    "env": {}
}
```

Hope this helps.

**Comment by juddey** [comment]
@davidlivingrooms Did you sort this, don't mind throwing something on this issue if that would help you.

**Comment by davidlivingrooms** [comment]
@juddey Do you have a different way than the vscode way? I don't mind trying any way that works so I'll use vscode if that is what most people are using. I'm curious if there's a different way that doesn't require me to install vscode just so that I can debug.

Also, the snippet I provided is the basic test that is found in most examples online. The application I'm actually building is a tray-only app and it seems like testing tray-only apps is still somewhat limited unfortunately https://github.com/electron/spectron/issues/90.

**Comment by juddey** [comment]
@davidlivingrooms The tests (and running them) do not depend on vscode. I run atom on linux and my tests work just fine - editor discussions are a bit of a red herring.

I think your code for the "debugger test" should look like: 
```javascript
  it('opens a window', function () {
     return app.client.debug();
  })
```
where you put the `return` is the key :)

I run my tests using yarn with mocha as my test runner:

![image](https://user-images.githubusercontent.com/7445602/28482316-edb331ec-6ebb-11e7-87ec-4779a192a2b4.png)

The `>` at the bottom of the window is the debugger, I've typed in `browser.getTitle()`, but you could use any valid webdriver command here. 

I quickly read #90 and that makes total sense, because a tray-only apps wouldn't have access to a webdriver context... so sounds like you might have your answer there for now.

**Comment by davidlivingrooms** [comment]
I'm gonna close this since my issue has more to do with the fact that i'm building a tray-only app. I look forward to using Spectron more later!

**Comment by Michenux** [comment]
You can also do:

```
it('opens a window', function () {
     app.browserWindow.openDevTools();
     return app.client.debug();
  })
```
