### ISSUE TITLE
electron app hanging around after tests on OSX

### ISSUE THREAD

**Issue by tansaku** [electron/spectron#229]
I'm on OSX 10.12.6 and using node 6.11.2 and electron 1.7.5

Everything going pretty smoothly but I notice that I have an electron app hanging around after tests are run - I can see it in the apps running on OSX.

I currently have the following code in `afterEach`

```js
    if (this.app && this.app.isRunning()) {
      return this.app.stop();
    }
  });
```

and am starting up like this:

```js
  beforeEach(function () {
    var electronPath = "./node_modules/.bin/electron";

    var appPath = ".";

    this.app = new Application({
                path: electronPath,
                args: ["--js-flags=--harmony", appPath, testFile],
                webdriverLogPath: './webdriverlogs',
                chromeDriverLogPath: './chromedriver.log'
    });

    var startingApp = this.app.start();

    return startingApp;
  });
```

is this expected? Is there something else I could do to ensure that the app completely quits after the tests ...

**Comment by tansaku** [comment]
I think I'm noticing a pattern - the app hangs around if the tests fail and/or if I'm using waitOn to try and wait for file resource to become available ...

**Comment by tansaku** [comment]
okay, and now it's happening all the time :-(

**Comment by jonolo6** [comment]
Are any processes running blocking the port? Console.log the app.chromeDriver somewhere in the test and check there if you see any log messages for any blocked ports. Or restart the computer. If that doesn't solve it you'll have to ask others since I'm not sure what those args you supply do.

**Comment by tansaku** [comment]
@jonolo6 I think we fixed it - we had the following in the code:

```
// Quit when all windows are closed (except on Mac)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

apparently that came from somewhere in https://electron.atom.io/docs/tutorial/quick-start/, but anyway I've removed that exception and we seem to be closing properly now.
