### ISSUE TITLE
Clarify version number matching specificity.

### ISSUE THREAD

**Issue by MattyBalaam** [electron/spectron#234]
Looking at the docs it is hard to tell if version numbers between Spectron and Electron need to exactly match. 

e,g, if I am using Electron 1.7.5, do I need to wait for a 3.7.5 release?

**Comment by MarshallOfSound** [comment]
@MattyBalaam Afaik only the minor versions need to match 👍

**Comment by MarshallOfSound** [comment]
> This minor version of this library tracks the minor version of the Electron versions released. So if you are using Electron 1.0.x you would want to use a spectron dependency of ~3.0.0 in your package.json file.
