### ISSUE TITLE
Possible to support puppeteer?

### ISSUE THREAD

**Issue by guiguan** [electron/spectron#240]
`webdriverio` sometimes can be slow and unreliable. [`puppeteer`](https://github.com/GoogleChrome/puppeteer) looks very promising. Any plan to support it in near future?

**Comment by guiguan** [comment]
Looks like in order for `puppeteer` to work, it needs a Chromium version >= 64.0.3240.0 I guess that would be a long waiting before `electron` can support that

**Comment by trusktr** [comment]
I think Puppeteer and Electron are very different. Maybe Puppeteer support means porting Puppeteer API to Spectron, so that Spectron has a similar API (but it isn't Puppeteer, and isn't using Puppeteer).
