### ISSUE TITLE
cannot start application

### ISSUE THREAD

**Issue by theBenRaskin** [electron/spectron#263]
Hello.

I started working with spectron, and to get me feet wet I wrote the following script:
``` javascript
var Application = require("spectron").Application;
var myapp = new Application({ path: "C:\\Users\\ben\\AppData\\Local\\app\\app.exe" });

myapp.start();
console.log("app now running");
myapp.stop();
console.log("app now closed");
```

However, when I run the script, I get the following result: 
```(node:13764) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Application not running```

I have a feeling this has something to do with how I input the application path. What am I doing wrong? Has anyone else had this issue?

**Comment by HairyMaclary** [comment]
Have you tried handling the start() command as a promise? Try something like:

`await myapp.start()`

**Comment by bendacoder** [comment]
I have, but it gives me even more errors.

**Comment by bendacoder** [comment]
I even tried doing
```javascript
myapp.start().then(function() {
  console.log("app now running");
});
```

It just freezes up on me.

**Comment by HairyMaclary** [comment]
I took your code and managed to get the same error. I fixed it by placing it inside a test suite and running with my testing framework, which for me is Jest. 
```
var Application = require("spectron").Application;
describe('Application launch', () => {

   beforeEach(() => {
      this.app = new Application({
         path: '/Applications/AppName/Contents/MacOS/App'
      });
      return this.app.start();
   });

   afterEach(() => {
      if(this.app && this.app.isRunning()) { 
         return this.app.stop(); 
      }
   });

   test('true is true', async () => {
      expect.assertions(1);
   
      expect(true).toBe(true);
   });
})

```

This is adapted from [here](https://www.packtpub.com/mapt/book/application_development/9781786464125/11/ch11lvl1sec58/introduction-to-spectron).

I then ran:

`npm run test-ui-singleFile`

which relates to this command in my package.json:

`"test-ui-singleFile": "jest testDoc"
`

**Comment by bendacoder** [comment]
@HairyMaclary tried your code. It works. Thank you! The part I find strange is that spectron does not want to work as a standalone framework, it has to be bound to a test framework.

**Comment by bendacoder** [comment]
@HairyMaclary I got somewhere. When I run the code, I receive the following error:
```cmd
> jest

 FAIL  .\spectronTest.test.js (6.275s)
  Application launch
    × true is true (5005ms)

  ● Application launch › true is true

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at node_modules/jest-jasmine2/build/queue_runner.js:72:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:633:19)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.952s, estimated 7s
Ran all test suites.
```
The application starts, however the timeout error is not letting me run tests.

**Comment by bendacoder** [comment]
The problem was that I whenever I opened the application, it continued running in the background, even when I closed the window. I just downloaded node-cmd and used a taskkill command to end all instances of the application. Afterwards, everything went smoothly.

**Comment by lizzie** [comment]
I got the same problem. I tried use system app, such as '/Applications/Notes.app/Contents/MacOS/Notes', got the same error.

When I closed the app, main process(test case) will rerun the app. `this.app.start().then(() => { console.log('not run in here');})`



related issue #296

**Comment by karthik1407s** [comment]
@theBenRaskin 
Hi,
I am having the same issue with starting the application. can you elaborate on applications running in the background and usage of taskkill to kill the opened instances of the application../

Thanks in advance,
Karthik
