### ISSUE TITLE
Error: timeout exceeded

### ISSUE THREAD

**Issue by vchimev** [electron/spectron#27]
Hi @kevinsawicki,

I gave a try to the sample [here](https://github.com/vchimev/spectron-sample). It successfully run the appp, but than it failed as follows:
```
application launch
    1) "before each" hook for "shows an initial window"


  0 passing (10s)
  1 failing

  1) application launch "before each" hook for "shows an initial window":
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

My repo: https://github.com/vchimev/spectron-sample

Any help would be appreciated,
@vchimev

**Comment by kevinsawicki** [comment]
@vchimev can you log from without the callback where you have the `assert` and see if it is getting called?

**Comment by vchimev** [comment]
@kevinsawicki It is not.

**Comment by kamesh-a** [comment]
`Easily test your Electron apps using ChromeDriver and WebdriverIO.`
@vchimev i am not sure whether it will work for other applications rather than electron based apps, is your calculator app is made from electron or default app of mac.

`'/Applications/Calculator.app/Contents/MacOS/Calculator'`

**Comment by vchimev** [comment]
Thanks @kamesh-a!

It is the default calculator on OS X. I just tried with a particular Electron app and it worked.
