### ISSUE TITLE
Possibility to configure require name

### ISSUE THREAD

**Issue by stofte** [electron/spectron#29]
Hello,

I'm currently trying to make use of spectron for my angular2 app. My index.html contains the following lines:

        window.electronRequire = require;
        delete window.require;
        delete window.exports;
        delete window.module;

This is needed because some of the code I load otherwise hook these symbols and that messes with the code loading. However, api.js seems to fail because the require symbol is deleted. Manually patching up api.js to use electronRequire makes things work fine, but this is obviously less than ideal 

Any suggestions for dealing with this?

**Comment by kevinsawicki** [comment]
> Any suggestions for dealing with this?

There is no workaround currently besides patching `api.js` directly.

We could add an API for this as an option to the `Application` constructor to support this use case.

**Comment by stofte** [comment]
Given that electron itself recommends deleting the symbols [themselves](https://github.com/electron/electron/blob/master/docs/faq/electron-faq.md#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron) that probably seems like the best option.

I looked at the code, and was thinking of some variation of window[someVar] and passing the value either via this or by arguments, but not sure that's the most elegant approach.

**Comment by kevinsawicki** [comment]
I've added support for a new `requireName` option to `Application` that you can now set to `electronRequire`. This was released in `3.0.1`.

**Comment by stofte** [comment]
Thanks alot of the quick fix. I'm up and running with 3.0.1 :+1:
