### ISSUE TITLE
why app.start() return Promise but no resolve

### ISSUE THREAD

**Issue by lizzie** [electron/spectron#296]
hey, I wrote test case use mocha and spectron. But I got following results:

```
  1) Application launch
       shows an initial window:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Timeout.<anonymous> (node_modules/.4.1.0@mocha/lib/runnable.js:238:19)
```

the test case code is like:
```
describe('Application launch', function () {
  this.timeout(10000)

  it('shows an initial window', (done) => {
    const app = new Application({
      path: '/Applications/Safari.app/Contents/MacOS/Safari',
      args: [path.join(__dirname, '..')]
    });
    app.start().then(() => {
      console.log('hihihi');
      done();
    }).catch(e => {
      console.log('e', e);
      done();
    })
  })

})
```

seems that in the app.start() , no resolve called , lead to Promise always pending.

debugger into Application

```
Application.prototype.start = function () {
  var self = this
  return self.exists()
    .then(function () { console.log(1); return self.startChromeDriver() })
    .then(function () { console.log(2); return self.createClient() }) <--- Stuck in here
    .then(function () { console.log(3); return self.api.initialize() })
    .then(function () { console.log(4); return self.client.timeouts('script', self.waitTimeout) })
    .then(function () { console.log(5); self.running = true })
    .then(function () { console.log(6); return self })
```

```
  "devDependencies": {
    "assert": "^1.4.1",
    "mocha": "^4.0.1",
    "spectron": "^3.8.0"
  },
```
why?

**Comment by daniloprates** [comment]
@lizzie were you able to fix this?

**Comment by BabuShoban** [comment]
Hi Team,

I am facing similar kind of issue  when launching the application, i am trying to open electron application using "spectron" as like above mentioned, it is returning the same error.

This ticket is closed with out solution provided. kinldy help me out of the same or provide any suggestions how to handle the promises for "app.start()" function.

it would be really help for quick responses.

code :
beforeAll(function(){
    jasmine.DEFAULT_TIMEOUT_INTERVAL= 120000;
    
   return app.start().then( function(){
        app.browserWindow.isVisible();
    
    })

error:

Error: Timeout - Async function did not complete within 5000ms 

Thanks,
