### ISSUE TITLE
Support Electron 2.x and 3.x

### ISSUE THREAD

**Issue by DarrenCook** [electron/spectron#319]
I notice the only change with moving from supporting 1.7.x to 1.8.x was changing the version number of chromedriver:
   https://github.com/electron/spectron/pull/264/files

Is it really that simple? Or are other changes involved?
Will the move to supporting electron 2.x be more complicated?

**Comment by tranducanh** [comment]
Spectron 3.8.0 doesn't support electron 3.0.0-beta.6

**Comment by remss** [comment]
Yes spectron 3.8 does not seems to support electron 3 for now. See #317

**Comment by vantruongt2** [comment]
Same with me

**Comment by DarrenCook** [comment]
Has everyone been using spectron 3.8 with Electron 2.x, then? No problems?
Not even a need to specify a different chromedriver?
(There seemed like quite a lot changed: https://electronjs.org/blog/electron-2-0#changes--new-features  but maybe none of that affects Spectron?)

**Comment by remss** [comment]
I believe Spectron 3.8 is not working with 2.x because ChromeDriver dependency is fixed to 1.8, which is the driver for Electron 1.8

**Comment by remss** [comment]
Spectron 4.0 has just been released and support Electron 2, using chromedriver 2.30

To support Electron 3 Spectron has to use electron-chromedriver 3 (with chromedriver 2.36)

With Spectron 4.0 my tests fail with Electron 3.0.0-beta.8. But if update the chromedriver.exe manually to 2.36 then my tests pass.

**Comment by manu-st** [comment]
Electron 3.0 was just released. When can we expect an updated version of Spectron?

**Comment by schontz** [comment]
Is there any timeline for Electron 3 support? Is there some dev work to be done or does the chromedriver just need to be updated?

**Comment by schontz** [comment]
This one looks fixed! Thank you.
