### ISSUE TITLE
How to click on an element in Multi Window?

### ISSUE THREAD

**Issue by flypie2** [electron/spectron#326]
How to click on an element in Multi Window?
For example:
I want to click on an element in another BrowserWindow which provide a ImgViewer and inspect it's action.

**Comment by ericyahhh** [comment]
@flypie2 If there's another window open and you want to click on an element inside of it you need to first focus Spectron/Webdriver to that window like described here: https://github.com/electron/spectron#clientwindowbyindexindex

**Comment by flypie2** [comment]
@ericyahhh  Thanks!
