### ISSUE TITLE
Element could not be located

### ISSUE THREAD

**Issue by Ericat** [electron/spectron#33]
I am trying to find an element on the page with `waitUntilTextExists`, but it cannot be found. Not sure if this is the right place, but I've decided to open up an issue in case somebody spots anything wrong with what I am doing:

```
return myApp.client.waitForVisible('.btn-add').then(function(text) {
   console.log(text);
});
```
Code [here](https://github.com/Ericat/hoot/blob/master/test/app-test.js#L44) and this is the element I am trying to find: [`.btn-add`](https://github.com/Ericat/hoot/blob/master/app/client/containers/app.jsx#L68).

I have tried different ways, including one similar to the [example here](https://github.com/electron/spectron/blob/master/test/example-test.js#L41), but none of them worked. I've captured the full error with catch: `An element could not be located on the page using the given search parameters.` 

Perhaps this belongs on the webdriver project?

**Comment by lishoulong** [comment]
@ericat why do you close this issue, I encounter this same question.  How do you solve this question?

**Comment by Praveer1981** [comment]
@lishoulong did you find the solution of this issue ?
