### ISSUE TITLE
waitForDisplayed() and isDisplayed() not functions 

### ISSUE THREAD

**Issue by astr0sl0th** [electron/spectron#355]
Getting an error thrown saying saying `waitForDisplayed()` and `isDisplayed()` are not functions of `this.app.client`.

Is this to do with the webdriver version?

**Comment by j-a-m-l** [comment]
You need to use that methods on an element: https://webdriver.io/docs/api/element/isDisplayed.html

**Comment by j-a-m-l** [comment]
Try V4: http://v4.webdriver.io/
