### ISSUE TITLE
Update to webdriver 5

### ISSUE THREAD

**Issue by alexstrat** [electron/spectron#363]
Webdriver 5 breaking changes here: https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#boom-breaking-change

**Comment by pumano** [comment]
@codebytere can you help with that?

**Comment by vladimiry** [comment]
There seems to be a work in progress https://github.com/electron/spectron/issues/349.  So can we have a single issue tracking point?

**Comment by vladimiry** [comment]
CC @eostrom

**Comment by alexstrat** [comment]
Indeed, definitely sorry I missed it.
