### ISSUE TITLE
Is it ok to add new tests in CoffeeScript?

### ISSUE THREAD

**Issue by DinisCruz** [electron/spectron#37]
I quite like its syntax and since Atom is mainly written in CoffeeScript this would also make it easier for Atom devs to use spectron:

![image](https://cloud.githubusercontent.com/assets/656739/15453842/9373f2c8-201c-11e6-8ab4-29d84452d6ec.png)

**Comment by kevinsawicki** [comment]
Spectron tests can be written in any language that transpiles to JavaScript so CoffeeScript, TypeScript, and babel should all be fine.

If you are asking specifically about adding tests to the spectron repo, then tests should be written in plain JavaScript, this repository will not use CoffeeScript, TypeScript, or Babel without a compelling reason.
