### ISSUE TITLE
Keep electron instance opened between tests

### ISSUE THREAD

**Issue by DinisCruz** [electron/spectron#42]
What is a good way to run multiple tests using the same electron window?

The test examples I have seen, tend to show the use of beforeEach and afterEach to start and stop the electron instance, but this has a 2 sec penalty per test

For example note how in the tests bellow the 'check Html' and 'check title' tool 2sec each

![image](https://cloud.githubusercontent.com/assets/656739/15466569/2bb0346a-20d2-11e6-83ca-8189a852b5e4.png)

Ideally I would like to keep an instance of Electron opened which I can then use on demand to load pages in the browser window (or to create new ones).

And yes I know that there are cases where we want to have a pristine browser session, but in most browser automation cases that is not really needed

**Comment by DinisCruz** [comment]
See https://github.com/electron/spectron/issues/39#issuecomment-220931287 for code sample and screenshot of running it in travis

**Comment by kevinsawicki** [comment]
> What is a good way to run multiple tests using the same electron window?
> The test examples I have seen, tend to show the use of beforeEach and afterEach to start and stop the electron instance, but this has a 2 sec penalty per test

With Mocha, use `before`/`after` instead of `beforeEach`/`afterEach` and the application will stay running and only be started and stopped.

Closing this out.
