### ISSUE TITLE
app.browserWindow is not available when node integration is set to false

### ISSUE THREAD

**Issue by DinisCruz** [electron/spectron#54]
FYI to others that might hit on this issue, when note integration is set to false, like this:

```javascript
app.on('ready', function () {
    mainWindow = new BrowserWindow({
        show      : false,
        x         : 1200,
        y         : -1000,
        width     : 500,
        height    : 400,
        webPreferences: {
            nodeIntegration: false }
    })
``` 

the ```app.browserWindow``` will not be available

I'm sure there is a good reason for that , but it caught me off guard and I spent a couple hours trying to figure out why my tests were failing and the browserWindow wasn't set

**Comment by kevinsawicki** [comment]
> I'm sure there is a good reason for that

This is expected, the API helpers provided by Spectron run code in the renderer processes so if the `browserWindow` is unavailable then the helpers will not be able to run. `app.browserWindow` relies on calling `require('electron').remote.getCurrentWindow()` in the window which won't work if `require` is undefined.

This can be supported though, see https://github.com/electron/spectron#node-integration for more details on how to support this in your app.

Closing this out.

**Comment by DinisCruz** [comment]
thx, one issue is that node integration opens up a number of security concerns (i.e. the page we're opening can attack the local box and execute commands as the logged in user)

**Comment by kevinsawicki** [comment]
> thx, one issue is that node integration opens up a number of security concerns

Yeah, I totally understand that, but hopefully running specs can be trusted and exposing the `require` function only to Spectron via a `preload` script is acceptable.

**Comment by watsoncj** [comment]
here's what i went with in a preload script:

```
if (remote.process.argv.indexOf('--insecure-test') > 1) {
    window.require = require;
}
```

**Comment by archer5** [comment]
I have node integration enabled, yet app.browserWindow is still displaying as undefined. Are there any other known issues that might be causing this?

**Comment by cyruscook** [comment]
Thanks, this got me stuck!
