### ISSUE TITLE
[Request] Provide typings for use with Typescript

### ISSUE THREAD

**Issue by JimiC** [electron/spectron#65]
Please consider the possibility to provide typings so we can use Typescript with our tests.

**Comment by 3n-mb** [comment]
Client (most of work here) already has typing in Definitely Typed tool under webdriverio name.

**Comment by mceachen** [comment]
This can be closed thanks to 506dcbba11. 👍

**Comment by Johnz86** [comment]
There is a problem with typings, which should be fixed:
```
type BasicAppSettings = {
....
    env?:object,
....
}
```
 env?:Object,

**Comment by JimiC** [comment]
'object' type is correct for typescript 2.2+

**Comment by fortuna** [comment]
This seems to be missing required dependencies. I'm getting:

```
node_modules/spectron/lib/spectron.d.ts(9,34): error TS7016: Could not find a declaration file for module 'webdriverio'. '/usr/local/xxx/home/xxx/xxx/xxx/node_modules/webdriverio/build/index.js' implicitly has an 'any' type.
  Try `npm install @types/webdriverio` if it exists or add a new declaration (.d.ts) file containing `declare module 'webdriverio';`
```
