### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by xelfe** [electron/spectron#66]
I would like to unit testing my electron into headless (on remote server). There's a sample app somewhere to see how to write a basic test from a sample application ? Spectron looks good for that but I cant figure how to apply this to a project.

**Comment by zeke** [comment]
Hi @xelfe. Have a look at https://github.com/electron/electron-api-demos/blob/master/tests/index.js -- that should get you started.

**Comment by xelfe** [comment]
@zeke Thank you. That help me a lot. On my side I had to put app.client.getWindowCount().should.eventually.equal(2) to make the test pass. I tried on linux and windows 10. Same result.

Also what about if I want to test a HTML tag ? I have a angular electron app that spawn \<home> tag when I click home. \<page1> if I click page1..etc

see the repo: [angular2-electron-starter](https://github.com/xelfe/angular2-electron-starter)
and my travis tests: [result](https://travis-ci.org/xelfe/angular2-electron-starter)

**Comment by kevinsawicki** [comment]
> . On my side I had to put app.client.getWindowCount().should.eventually.equal(2) to make the test pass.

Are you using a `<webview>` tag? That counts as a window technically which might explain why the count needed to be updated in your case.

> Also what about if I want to test a HTML tag ?

You may want to check out the webdriver docs (which spectron builds on top of) which has lots of helpers for getting the state of your page and interacting with it.

http://webdriver.io/api.html
