### ISSUE TITLE
client.execute does not work if app closes initial window and opens another

### ISSUE THREAD

**Issue by hiddentao** [electron/spectron#69]
I have an app whose startup sequence is as follows:

1. Show splash window for 5 seconds...then close it
2. Open and show main app window

I wait for 10 seconds in my tests before issuing commands via the APIs. However they don't work because `client.execute()` doesn't work - and I think this is because the webdriver `client` API gets initialized agains the splash window since that shows up first - am I right?

How can I make it so that I can issue commands agains the main app window?

**Comment by kevinsawicki** [comment]
> How can I make it so that I can issue commands agains the main app window?

Does your main window have focus?

You can toggle which window commands get run using the https://github.com/electron/spectron#clientwindowbyindexindex API or one of the http://webdriver.io/api/protocol/window.html API.

Here is an example spec that checks multiple windows: https://github.com/electron/spectron/blob/fa824d66b26b47e2c06d4b3eddb0de372d31ad40/test/multi-window-test.js#L24-L42

Does that help?

**Comment by hiddentao** [comment]
Thanks. I managed to bypass the problem by simply never showing the splash screen but I'll try your suggestion and let you know.

**Comment by kevinsawicki** [comment]
> I managed to bypass the problem by simply never showing the splash screen but I'll try your suggestion and let you know.

Closing this out for now, please comment if you think this is an addressable issue.
