### ISSUE TITLE
The last time you opened Kno2 Desktop, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?

### ISSUE THREAD

**Issue by dougludlow** [electron/spectron#73]
I'm following the examples in the README on OS X, but I get the following popup with the following message whenever it runs the beforeEach to start the app again:

> The last time you opened Kno2 Desktop, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?

Anyone else running into this issue?

**Comment by kevinsawicki** [comment]
> The last time you opened Kno2 Desktop, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?

This means the app crashed. It should only show this the first time the app is launched after a crash. I'm not sure if there is a way to disable this dialog.

**Comment by dougludlow** [comment]
@kevinsawicki so the `this.app.stop()` is crashing the app?

**Comment by dougludlow** [comment]
This is basically what I'm doing:

```
var Application = require('spectron').Application
var chai = require('chai')
var chaiAsPromised = require('chai-as-promised')
var path = require('path')

chai.should()
chai.use(chaiAsPromised)

describe('application launch', function () {
  beforeEach(function () {
    this.app = new Application({
      path: '/Applications/MyApp.app/Contents/MacOS/MyApp'
    })
    return this.app.start()
  })

  beforeEach(function () {
    chaiAsPromised.transferPromiseness = this.app.transferPromiseness
  })

  afterEach(function () {
    if (this.app && this.app.isRunning()) {
      return this.app.stop()
    }
  })

  it('opens a window', function () {
    return this.app.client.waitUntilWindowLoaded()
      .getWindowCount().should.eventually.equal(1)
  })
})
```

**Comment by kevinsawicki** [comment]
@dougludlow if you open the `Console.app` on Mac, do you see these crashes on the left hand side?

**Comment by dougludlow** [comment]
I see this:
<img width="313" alt="screen shot 2016-06-29 at 11 23 35 am" src="https://cloud.githubusercontent.com/assets/733821/16461879/f57daa44-3deb-11e6-9a31-aa49257de3ea.png">

**Comment by kevinsawicki** [comment]
@dougludlow 

Can you expand User Diagnostic Reports and see if it shows any Kno2 crashes there?

**Comment by dougludlow** [comment]
Ok, yup I do. So it is somehow crashing...

**Comment by dougludlow** [comment]
Thanks for pointing that out. Must be the way I'm quitting my app from electron. Thanks for your help @kevinsawicki.

**Comment by kevinsawicki** [comment]
Yeah, it could be an Electron bug so you might want open an issue there depending on what the stack trace looks like.

**Comment by blainesch** [comment]
@dougludlow did you ever figure out the issue? I'm running into a similar issue.

**Comment by dougludlow** [comment]
@blainesch yes, I had logic in the before-quit that was running asynchronously and not completing before the application quit.
