### ISSUE TITLE
Getting started with Spectron

### ISSUE THREAD

**Issue by violinner** [electron/spectron#81]
Having created an electron application with a main.js and an index.html, 
And it runs with a GUI on the command:

       node_modules/.bin/electron .
or

       npm start

Using the Spectron "Get Started" example, saving "a sample test" as "testApp.js", 
What should be the value of: 

       var app = new Application({ path: ' ??? ' })

And what is the command to invoke this code, which runs the GUI app and performs the test?

Clearly it is not "node testApp.js", or I have not configured things correctly.

Thanks!

**Comment by zeke** [comment]
Hi, @violinner. Take a look at the `electron-api-demos` codebase. That should get you started:

https://github.com/electron/electron-api-demos/blob/3afe1789efbec9b15b0ee04d10cb0bdacb537ed2/package.json#L12

https://github.com/electron/electron-api-demos/blob/3afe1789efbec9b15b0ee04d10cb0bdacb537ed2/tests/index.js

**Comment by violinner** [comment]
Zeke,  great demo and starting point for electron.
How can I run the test in tests.index.js?  This is where my original question comes in.
This does not work:

      electron tests/

**Comment by zeke** [comment]
> How can I run the test in tests.index.js?

The command to run the tests is specified in package.json under `scripts.test`.

To run the tests, type `npm test`

To see all the scripts you can run, type `npm run`

**Comment by violinner** [comment]
"npm test" runs a mocha test that fails, apparently on initialization. 

Should the app be started first, or is the test intended to launch the app? 

The electron demo app Gui did not start automatically, but can be run by itself.

**Comment by zeke** [comment]
I see you opened another ticket at https://github.com/electron/electron-api-demos/issues/242 -- we can continue there.
