### ISSUE TITLE
Windows Chromedriver timeout issue

### ISSUE THREAD

**Issue by amilajack** [electron/spectron#86]
My spectron tests work perfectly on macOS and linux but they dont seem to start on windows. Here's the code I have to initialize spectron:

```js
// ...
const app = new Application({
  path: path.join(__dirname, '..', 'node_modules', '.bin', 'electron'),
  args: [
    path.join(__dirname, '..', 'app')
  ],
  waitTimeout: 2000
});

console.log(path.join(__dirname, '..', 'node_modules', '.bin', 'electron'));
console.log(path.join(__dirname, '..', 'app'));
```
And here' the output of the tests:
```
  1) e2e "before all" hook:
     Error: ChromeDriver did not start within 5000ms
      at Error (native)
      at C:\Users\amila\Documents\Projects\popcorn-time-desktop\node_modu
      at Request._callback (C:\Users\amila\Documents\Projects\popcorn-tim
      at self.callback (C:\Users\amila\Documents\Projects\popcorn-time-de
      at Request.onRequestError (C:\Users\amila\Documents\Projects\popcor
      at Socket.socketErrorListener (_http_client.js:306:9)
      at emitErrorNT (net.js:1272:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

It seems that ChromeDriver isnt starting on windows. Any suggestions on why this is happening?

**Comment by jhen0409** [comment]
The command file should be `node_modules/.bin/electron.cmd` for Windows, so I recommend use `require('electron-prebuilt')` to get binary path.

**Comment by amilajack** [comment]
I've updated it to this:

```js
const app = new Application({
  path: require('electron-prebuilt'),
  args: [
    path.join(__dirname, '..', 'app')
  ],
  waitTimeout: 2000
});
```

And I'm still getting the same result.

**Comment by Aerlinger** [comment]
Having a similar issue. It may be helpful to have examples for using spectron with electron-prebuilt. I would assume this is a much more relevant use-case for most people than linking to a prebuilt electron app.

**Comment by MarshallOfSound** [comment]
Not sure if this helps anyone but this is the test harness I wrote to handle cross platform launching of spectron without having to repackage every time.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/test/spectron/util/_harness.js

The launch path determining bit is
```js
let appPath;
if (process.platform === 'win32') {
  appPath = path.resolve(
    __dirname,
    '../../../node_modules/electron-prebuilt/dist/electron.exe'
  );
} else if (process.platform === 'darwin') {
  appPath = path.resolve(
    __dirname,
    '../../../node_modules/electron-prebuilt/dist/electron.app/Contents/MacOS/electron'
  );
} else {
  appPath = path.resolve(
    __dirname,
    '../../../node_modules/electron-prebuilt/dist/electron'
  );
}
```

**Comment by jhen0409** [comment]
It looks work fine with [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate/blob/master/test/e2e.js):

![erb-win7](https://cloud.githubusercontent.com/assets/3001525/16860347/e91357ba-4a69-11e6-9cb5-a94fb1885711.png)

And [my project](https://github.com/jhen0409/react-native-debugger/blob/master/test/e2e/app.spec.js):

![rnd-win7](https://cloud.githubusercontent.com/assets/3001525/16860056/e6f3544c-4a66-11e6-9d42-0de7ea4f55b7.png)


Just make sure `node_modules/electron-chromedriver/bin/chromedriver.exe` is exists, I can get the same error if I removed it.

**Comment by amilajack** [comment]
I'm running this inside of a windows 10 VM which doesnt come with visual studio and what not. I've tried deleting the `node_modules` directory and doing an `npm i` and found out that I'm getting a `node-gyp` error when compiling native deps. Hopefully it'll work after installing visual studio and other compiling dependencies.

**Comment by amilajack** [comment]
Test passes on appveyor. Thanks a bunch @jhen0409!

**Comment by hovancik** [comment]
This should definitely be in docs somewhere. Took me days to find this discussion.

**Comment by amilajack** [comment]
> This should definitely be in docs somewhere

Agreed! Seems like a lot of ppl would benefit from that
