### ISSUE TITLE
API to test clicking a menu item

### ISSUE THREAD

**Issue by violinner** [electron/spectron#92]
What is the syntax of a Spectron chaiAsPromised test to click a browser window menu item "View" and then sub-item "Details"?  
Is there something along the order of:
    ...click('button[id="submit-survey"]')
?

**Comment by kevinsawicki** [comment]
This is not currently supported, see https://github.com/electron/spectron/issues/21 for more details.

**Comment by CapOM** [comment]
Is this working with https://www.npmjs.com/package/spectron-menu-addon ?
