### ISSUE TITLE
app.client inaccessible

### ISSUE THREAD

**Issue by ThibaultFriedrich** [electron/spectron#99]
I am using spectron with mocha. All functions which don't use app.client work very well like 
```
  it('screenshot', function (done) {
    this.app.browserWindow.capturePage().then(function (imageBuffer) {
      fs.writeFile(__dirname+'/page.png', imageBuffer, function () {
        done();

      });
    });
  });
```

It opens the window, take a screenshot and close the window.

But all functions like `this.app.client.getTitle()`, `this.app.client.getWindowCount()` or `this.app.client.getText('#title')` totally mess up. For example `getWindowCount()` returns 2 whereas there is only one window.

Do you know the origin of this bug ?

**Comment by MarshallOfSound** [comment]
@ThibaultFriedrich `getWindowCount()` includes webviews in the count.  Do you have one window and a WebView?

**Comment by ThibaultFriedrich** [comment]
I'm not sure what you mean by "WebView" but I don't think so.This is my renderer code 

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset='utf-8' />
		<title>Elqui</title>
	</head>
	<body>
    <div id="title">
      Hello world
    </div>
  </body>
</html>
```

And the problem happens for `getWindowCount()` but also for `getText('#title')` or others functions of client.

**Comment by MarshallOfSound** [comment]
Do you have a `waitUntilWindowLoaded()` in your test code?

**Comment by ThibaultFriedrich** [comment]
Oui voici mes deux premiers tests, qui fonctionnent très bien

```
it('shows an initial window', function (done) {
    this.app.client
    .waitUntilWindowLoaded()
    .then(function () {
        done();
     });
});

it('is visible', function (done) {
    this.app.browserWindow.isVisible().then(function (visible) {
         expect(visible).to.be.true;
         done();
    });
});

```

**Comment by kevinsawicki** [comment]
> But all functions like this.app.client.getTitle(), this.app.client.getWindowCount() or this.app.client.getText('#title') totally mess up

What do you mean by mess up? Just return the wrong values? What is `app.client.getTitle()` returning?

Can you include a sample app that demonstrates the incorrect behavior?

**Comment by ThibaultFriedrich** [comment]
For example, I try to test the title 
```
    it('has the good title', function (done) {
        this.app.browserWindow.getTitle().then(function (title) {
            expect(title).to.be.equal('Elqui');
            done();
        });
        //console.log(this.app.client.getWindowCount());
    });
```
 
The title seems to be empty whereas I setup a title in the html.

When I try to test the windows cout
```
    it('one windows', function (done) {
        this.app.client.getWindowCount().then(function (count) {
            console.log(count);
            done();
        });
    });
```

It returns 2 whereas I have only one window.

And finally when I want to access to a div in my user interface.

```
   it('one windows', function (done) {
        this.app.client.getText('#title').then(function (errorText) {
            console.log('The #error-alert text content is ' + errorText);
            done();
        });
    });
```

It blocks and mocha fails because of a timeout.

It is like everything about client is not right whereas the tests about the browserWindow are OK. Something about selenium is may not really started ?

**Comment by Mercieral** [comment]
I am also trying to use app.client.getTitle() and it is always returning an empty string for me. 
```javascript
    it('should start in the organization select page', (done) => {
        app.client.getTitle().then((title)=>{
            console.log( '[' + title + ']' );
            done();
        });
    });
```

The title is getting set correctly on the web version of my application. I just have a simple `<title>` element in my html header.

**Comment by Mercieral** [comment]
The problem is both you and I have the devTools open on the Electron application. It seems that spectron's app.client only refers to the devtools window and not the main application window. This is why you are getting a window count of 2, and no values for getTitle/getText. 

Is there any way for Spectron to ignore the devtools window alltogether?

**Comment by MarshallOfSound** [comment]
@Mercieral If Spectron considers the Dev Tools a window (I.e. it's own renderer process) you can target a different window with 

https://github.com/electron/spectron#clientwindowbyindexindex

```js
client.windowByIndex(1)
```

**Comment by ThibaultFriedrich** [comment]
AAAhhhhh ! Ok I did know that Spectron considers the Dev Tools a window. When I desactivate the dev tools there is no more problem. That is perfect for me ! 

Thanks @MarshallOfSound and @Mercieral. Spectron is really a good framework. I gonna fall in love ;).

**Comment by Mercieral** [comment]
@MarshallOfSound I agree that would solve the issue, but it seems more of a workaround as many developers working with Electron will show the devTools when testing their applications. 

This would mean that everyone who uses the devTools would have to know this and either add that line or remove the devTools for testing.

**Comment by ThibaultFriedrich** [comment]
You may use a environment variable or a argument of your application in order to hide the devTools with spectron. In fact, they wont be there in production.

**Comment by kevinsawicki** [comment]
> As for ignoring Dev Tools windows @kevinsawicki ?

I'll have to take a look about what information ChromeDriver returns for dev tools windows to see if they can be distinguishes from regular browser windows.

**Comment by kevinsawicki** [comment]
> As for ignoring Dev Tools windows @kevinsawicki ?

I'll have to take a look about what information ChromeDriver returns for dev tools windows to see if they can be distinguishes from regular browser windows.
